name: task_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  google_fonts: ^6.2.1
  http: ^1.2.1
  iconly: ^1.0.1
  liquid_pull_to_refresh: ^3.0.1
  lottie: ^3.1.0
  mockito: ^5.4.4
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sqflite: ^2.3.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
